# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: callattendant
version: "1.0.0"
slug: callattendant
description: Phone blocker and voice message system
url: "https://github.com/guyfawkes73/homeassitant-addon/callattendant"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
ingress: true
startup: application
ports:
  5000/tcp: 5000
uart: true
devices:
  - /dev/ttyACM0
#image: "ghcr.io/guyfawkes73/{arch}-addon-callattendant"
map:
  - share:rw
options:
  debug: False
  screening_mode: ("whitelist","blacklist")
  SCREENED_ACTIONS: ("ignore",)
  blocked_actions: ("answer","record_message")
  mqtt:
    mqtt_broker_url: localhost
    mqtt_broker_port: 1883
    mqtt_username: mqtt_user
    mqtt_password: mqtt_pwd
    mqtt_keepalive: 60
schema:
  debug: "match(True|False)"
  screening_mode: str
  SCREENED_ACTIONS: str
  blocked_actions: str
  mqtt:
    mqtt_broker_url: str
    mqtt_broker_port: int
    mqtt_username: str
    mqtt_password: str
    mqtt_keepalive: int
